# **Libraries**

In [1]:
import math
math.sqrt(25)

5.0

In [2]:
def square_rt(n):
  return n**0.5

square_rt(25)


5.0

**use of Libraries**                         
 - maths and calcuations                      
 - Files                       
 - websites and internet                      
 - Data processing                      
 - Graohs and charts                      
 - Dates and time                       
 - Database                              
 - Machine Learning models                   

In [ ]:
import numpy as np
numbers =[10,20,30] #Python list
'''list are unorganized datatype in which we can use multiple data types '''

number=np.array([10,20,30]) #Numpy array
'''arrays are organized datatset in which only same type of datatypes can be use'''

In [6]:
print(numbers)
print(number)

[10, 20, 30]
[10 20 30]


In [ ]:
numbers = [10 ,20 ,30] #list
result=[]

for n in numbers:
  result.append(n*2)
result
'''Execution flow----
in for loop , every number in list "numbers" will multiply with 2 amd the result will be append in empty result =[] variable 
at last.... we call the updated result  '''

[20, 40, 60]

In [ ]:
numbers = np.array([10,20,30]) #arrays
result = numbers*2
result
''' In arrays ... every element will multiply with 2 and the output will store in result...
result is actually a new array in which output is stored '''

array([20, 40, 60])

In [13]:
np.zeros(5) #creat array of zeroes



array([0., 0., 0., 0., 0.])

In [14]:
np.ones(5) #create array of 1

array([1., 1., 1., 1., 1.])

In [ ]:
np.arange(0,10,2) #array starts from 0 upto 10 and increments with 2

array([0, 2, 4, 6, 8])

In [ ]:
numbers =np.array([10 , 20 , 30])
numbers[0] #accessing value from the array


np.int64(10)

In [17]:
numbers[1] = 99 # to swap number od particular element in the array
numbers

array([10, 99, 30])

**Basic arithmetic operations with array**

In [18]:
numbers =np.array([10 ,20 ,30])
numbers + 5

array([15, 25, 35])

In [19]:
numbers *2

array([20, 40, 60])

In [20]:
numbers / 10

array([1., 2., 3.])

In [21]:
a = np.array([10 ,20 ,30])
b = np.array([1 ,2 ,3])
a +b #adding elements of two arrays

array([11, 22, 33])

In [22]:
a*b

array([10, 40, 90])

In [23]:
np.sum(numbers) #sum of all values in array

np.int64(60)

In [26]:
np.mean(numbers) #gives arithmetic mean of array

np.float64(20.0)

In [25]:
np.max(numbers) #gives maximum values form the array

np.int64(30)

In [28]:
numbers = np.array([  #matrix
    [1 ,2 ,3],
    [4 ,5,6]
])
numbers.shape

(2, 3)

In [ ]:
numbers[0,1] #access specific element from the matrix using Variable[row,column] syntax

np.int64(2)

**URL :inbuild**

In [ ]:
import urllib.request #use to fetxh web pages info
response = urllib.request.urlopen('https://google.com')
response.status #200 means success

200

In [31]:
pip install requests

In [32]:
#requests  is a third parth option of urllib library which is simpler that urllib
import requests
requests.get(
    'https://google.com'
)

<Response [200]>